version: '3.8'
services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_air_container
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres_air
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres_air.sql:/docker-entrypoint-initdb.d/postgres_air.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
